name: Workflow 1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Hello World
        run: echo "Hello World!!"
      - name: Create File
        run: touch ./test
      - name: List Files
        run: ls -la
      - name: Clean up
        run: rm ./test
